# .streamlit/secrets.toml
# 아래 경로를 본인 환경에 맞게 수정하세요

# Windows 예시
#DC_WEGOVY_PATH = "C:\Users\kim20\Downloads\wegovy_dc_1.json"
#DC_MOUNJARO_PATH = "C:\Users\kim20\Downloads\mounjaro_dc_2.json"   # 파일 생기면 여기에 추가
#REDDIT_PATH = "G:/My Drive/Reddit_v8.jsonl"

# Mac 예시
# DC_WEGOVY_PATH = "/Users/이름/Downloads/wegovy_dc_1.json"
# DC_MOUNJARO_PATH = ""
# REDDIT_PATH = "/Users/이름/Google Drive/My Drive/Reddit_v8.jsonl"

DC_WEGOVY_PATH = "wegovy_dc_1.json"
DC_MOUNJARO_PATH = "mounjaro_dc_2"
REDDIT_PATH = "Reddit_v8.jsonl"
