# .streamlit/secrets.toml
# 아래 경로를 본인 환경에 맞게 수정하세요

# Windows 예시
#DC_WEGOVY_PATH = "C:\Users\kim20\Downloads\wegovy_dc_1.json"
#DC_MOUNJARO_PATH = "C:\Users\kim20\OneDrive\문서\대학-이화\3학년\DE_prj1_v2\mounjaro_dc_2.jsonl"   # 파일 생기면 여기에 추가
#REDDIT_PATH = "C:\Users\kim20\OneDrive\문서\대학-이화\3학년\DE_prj1_v2\Reddit_v8.jsonl"

# Mac 예시
# DC_WEGOVY_PATH = "/Users/이름/Downloads/wegovy_dc_1.json"
# DC_MOUNJARO_PATH = ""
# REDDIT_PATH = "/Users/이름/Google Drive/My Drive/Reddit_v8.jsonl"

REDDIT_PATH = "Reddit_v8.jsonl"

COSMOS_URI =  "mongodb+srv://DEproject1:sksmsskawo123!@nje-cluster.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
COSMOS_DB = "DEproject"
COLLECTION_w = "dc_wegovy_cleaned_final"
COLLECTION_m = "dc_test_cleaned_final"